# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaf3677856f24db7d600135ed2727ef93c9078dc86cb573e5c8ebebece362f67765eaf5d40663c0bfc15c86de72f394e97f9d0b86f0e704ace1c6e63919d414a

test:
  secret_key_base: 93cb27b785f0a3e03d49b59a7fa825119702fc9ce1869d1645d5a0bf99757c9567e79795c91dcf7ab83088c4300e95e8081ee28ca3c341b4373074a04cad307d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
